apiVersion: v1
kind: Service
metadata:
  name: uploader
  namespace: uploader
spec:
  ports:
  - nodePort: 32393
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: uploader
  type: NodePort
